### ISSUE TITLE
call out block for not-quite-finalized chapter

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#105]
@JohannaLoomba & @oneilsh, you seemed to be the people most interested in declaring the chapters that were migrated, but not yet finalized.  How do you feel about a callout block that says:

> This chapter is being finalized.  The content might change a little.  Most of the remaining work involves formatting and cross references to other chapters.  We hope to complete this chapter during May 2023.

![image](https://user-images.githubusercontent.com/1372890/235761607-ec761e39-73ce-428c-8e5f-a03448eb1d58.png)

**Comment by JohannaLoomba** [comment]
Hi Will,

Since you asked…how about this slightly different version:

This chapter is undergoing final edits, including formatting and cross referencing.  Edits are expected to complete by June 2023.
Johanna


From: Will Beasley ***@***.***>
Sent: Tuesday, May 2, 2023 2:57 PM
To: National-COVID-Cohort-Collaborative/guide-to-n3c-v1 ***@***.***>
Cc: JohannaLoomba ***@***.***>; Mention ***@***.***>
Subject: [National-COVID-Cohort-Collaborative/guide-to-n3c-v1] call out block for not-quite-finalized chapter (Issue #105)


@JohannaLoomba<https://github.com/JohannaLoomba> & @oneilsh<https://github.com/oneilsh>, you seemed to be the people most interested in declaring the chapters that were migrated, but not yet finalized. How do you feel about a callout block that says:

This chapter is being finalized. The content might change a little. Most of the remaining work involves formatting and cross references to other chapters. We hope to complete this chapter during May 2023.

**Comment by wibeasley** [comment]
Thanks, @JohannaLoomba.  I like that better.  Here's what it looks like now.

![image](https://user-images.githubusercontent.com/1372890/236080850-20ceaac0-81ae-4417-a015-4d9d14c250d3.png)
