### ISSUE TITLE
Chapter 6 states Level 1 data is still available - I don't believe this is correct

### ISSUE THREAD

**Issue by tradman** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#173]
Chapter 6 states: 
>Update: As of mid-2022, N3C is no longer able to generate new synthetic datasets at researcher request. The previously-generated datasets are still available for use however, and gaining access to Level 1 data provides access to all generated synthetic datasets.

However, I work on the N3C DAC committee and my understanding is this level is not available for request at all.  Is this correct?  Perhaps we can edit this page, and even remove all mentions of Level 1 data altogether because if it is not available we are just wasting peoples time making them read through the details of Level 1.  A good part of chapter 6 describes the Level 1 data construction.

**Comment by oneilsh** [comment]
@tradman thanks, sorry it's taken so long to follow up on github issues ;)

It's a good point. It seems that level 1 is still an option for new DURs in the enclave, and the data are still there, but the links to them have been removed from the data catalog. 

Given that we aren't generating new level 1 synthetic data either (and the utility of the existing data is extremely limited), I agree that we should strip out most mention of it from the guide. So that readers aren't confused by the counting starting at level 2, I might leave a "stub" in that mentions what level 1 data was and that it has been deprecated. 

Thoughts?

**Comment by wibeasley** [comment]
I like that L1 has a placeholder so it doesn't start at L2.  Also if L1 is revived, now much has to be re-re-written.
