### ISSUE TITLE
Chapter 9, practices.md,  headings switch to Chapter 12 after the table in sec. 9.3.4

### ISSUE THREAD

**Issue by chrisroederucdenver** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#182]
The section "Protocol Development is numbered 12.1". Oddly this comes right after a table whose columns are number 10, 11 and 12.

**Comment by wibeasley** [comment]
That is weird.  I'll check it out.  I'm sure it didn't look that way when I translated the chapter a year ago.

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/0d3f154e-cd5d-4588-9e9c-6e2351096d81)
...
![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/2f29c211-86ee-42a2-b6ff-5521df3f5608)

**Comment by wibeasley** [comment]
I'm guessing the pandoc parser is getting confused by the alternative style of specifying a table.  The table header uses a `===============` line.

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/63064559-b795-44dd-9ca4-404090d14605)

I had to specify the table in this style because they wanted multiple bullets in a table cell.

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/d6479d38-8c3c-404e-835b-fc7234765019)

**Comment by wibeasley** [comment]
filed a bug on the quarto repo: https://github.com/quarto-dev/quarto-cli/issues/8732
