### ISSUE TITLE
Author block for Help & Support chapter not showing

### ISSUE THREAD

**Issue by oneilsh** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#208]
Even with PR #205. Not sure why 🤔

**Comment by wibeasley** [comment]
I think this was fixed with https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/pull/205/commits/2c098f72dd50c5d17acdcd006bf9de520d75d631

It fixed the error with the title-block, and we got our ORCiD back.  With new email icons too.

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/ae8b8d2d-419c-4c50-be3c-808e0c970874)

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/a5988c6f-e251-437c-a417-e18b6e1aceb2)

**Comment by chrisroederucdenver** [comment]
Good job. I broke down and learned a bit about the expression language and got this far (affiliations don't work). The canned stuff that appears is very nice.
```
    $for(by-author)$
        <p> 
        $by-author.name.literal$
        $by-author.email$
        $by-author.orcid$
        $if(by-author.attributes.corresponding)$
           corresponding author
        $endif$
        <br> $by-author.affiliation$
        <br> $by-author.affiliation-url$
        </p>
    $endfor$
```

**Comment by wibeasley** [comment]
@chrisroederucdenver, it's fine with me if you and @oneilsh want to tweak it from the vanilla.

I think the three of us have similar tradeoffs between style & maintainability.

**Comment by chrisroederucdenver** [comment]
Sometimes vanilla is really good. I might tweak further if the affiliations above worked. Since they don't, and you found such good vanilla that has icons etc., I'm backing away from a rabbit hole.
